polls/mypolls/urls.py
from django.urls import path
from mypolls import views

app_name = 'polls'

urlpatterns = [
    path('', views.index),
    path('<int:question_id>/', views.detail),
    path('<int:question_id>/vote', views.vote, name="vote"),
    path('<int:question_id>/results', views.results, name='results')
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include
from mypolls import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('mypolls.urls')),
    path('', views.index),
    path('predict/', include('restapi.urls')),
]

polls/restapi/urls.py
from django.urls import path
from restapi import views

app_name='api'

urlpatterns = [
    path('knn/', views.knn),
]

polls/mypolls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

polls/mypolls/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice
# Create your views here.

def index(request):
    latest_questions = Question.objects.all().order_by('-pub_date')[:5]
    context = {"latest_questions":latest_questions}
    return render(request, "mypolls/index.html", context)
    
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'mypolls/detail.html', context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    select_choice = question.choice_set.get(pk=request.POST['choice'])
    select_choice.votes += 1
    select_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=[question.id]))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'mypolls/results.html', context)

polls/restapi/views.py
from django.shortcuts import render
from django.urls import reverse
import pickle
from rest_framework.decorators import api_view
from rest_framework.response import Response
import numpy as np
# Create your views here.

@api_view(['POST'])
def knn(request):
    with open('./restapi/knn_class_model.pkl.pk', 'rb') as f:
        knn_class_model = pickle.load(f)
    w = float(request.data.get('weight'))
    l = float(request.data.get('length'))
    data_arr = np.array([w,l])
    data_scaled = (data_arr - knn_class_model['mean'])/knn_class_model['std']
    if knn_class_model['model'].predict(data_scaled.reshape(1,2)).tolist()[0] == 0.0:
        return Response({"result":"빙어"})
    else: return Response({"result":"도미"})

polls/templates/mypolls/detail.html
<head>
</head>
<body>
    <h1>
        {{question.question_text}}
    </h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote" />
    </form>

</body>

polls/templates/mypolls/index.html
{% if latest_questions %}
    {% for question in latest_questions %}
        <li>
            <a href="/polls/{{ question.id }}"> {{ question.question_text }} </a>
        </li>
    {% endfor %}
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/mypolls/results.html
<head>
    <h1>
        {{ question.question_text}} 
     </h1>
</head>
<body>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} : {{choice.votes}}</li>
        {% endfor %}
    </ul>
</body>