pybo/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

pybo/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index
from chart.views import chart

urlpatterns = [
    path('admin/', admin.site.urls),
    path("main/", include('main.urls')),
    path("common/", include('common.urls')),
    path("chart/", chart),
    path('', index, name="index")
]

pybo/main/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'main'

urlpatterns=[
    path('', base_views.index, name="index"),
    path('<int:question_id>/', base_views.detail, name="detail"),
    # question_views
    path('question/create/', question_views.question_create, name="question_create"),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    # answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name="answer_modify"),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name="answer_delete"),
]

pybo/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    class Meta:
        model = User
        fields= ("username", "email")
    

pybo/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm

# Create your views here.

def signup(request):
    if request.method=="POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {"form":form})
    

pybo/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>Login</h4>
        </div>
        <div class="col-8 text-right">
            <span><a href="{% url 'common:signup' %}">Create Account</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_error.html" %}
        <div class="form-group">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

pybo/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<!--sign up page-->
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>Create Account</h4>
        </div>
        <div class="col-8 text-right">
            <span><a href="{% url 'common:login' %}">Login</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_error.html" %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">Password check</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock %}