pybo/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index
from chart.views import chart

urlpatterns = [
    path('admin/', admin.site.urls),
    path("main/", include('main.urls')),
    path("common/", include('common.urls')),
    path("chart/", chart),
    path('', index, name="index")
]

pybo/main/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'main'

urlpatterns=[
    path('', base_views.index, name="index"),
    path('<int:question_id>/', base_views.detail, name="detail"),
    # question_views
    path('question/create/', question_views.question_create, name="question_create"),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    # answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name="answer_modify"),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name="answer_delete"),
]

pybo/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    emotion = models.TextField()
    is_positive = models.IntegerField(null=True)
    probability = models.FloatField(null=True)
    def __str__(self):
        return self.content

pybo/main/forms.py
from django import forms
from .models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {'subject':'subject',
                  'content':'content'}
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content':'content'}

pybo/main/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from ..models import Question, Answer
from ..forms import QuestionForm, AnswerForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .model_views import predict_sentence_positivity


@login_required(login_url='common:login')
def answer_create(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    if request.method=="POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = q
            result = predict_sentence_positivity(answer.content)
            answer.is_positive = result['is_positive']
            answer.probability = result['prob']
            answer.save()
            return redirect('main:detail', question_id=q.id)
    else:
        form = AnswerForm()
    context = {"question":q, "form":form}
    return render(request, 'main/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    a = get_object_or_404(Answer, pk=answer_id)
    if request.user != a.author:
        messages.error(request, "No Authority to modify this answer!")
        return redirect('main:detail', question_id=a.question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=a)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            result = predict_sentence_positivity(answer.content)
            answer.is_positive = result['is_positive']
            answer.probability = result['prob']
            answer.save()
            return redirect('main:detail', question_id=a.question.id)
    else:
        form = AnswerForm(instance=a)

    context = {'answer' : a, 'form' : form}
    return render(request, 'main/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    a = get_object_or_404(Answer, pk=answer_id)
    if request.user != a.author:
        messages.error(request, "No Authority to modify this answer!")
        return redirect('main:detail', question_id=a.question_id)
    else:
        a.delete()
    return redirect('main:detail', question_id=a.question_id)

pybo/main/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from ..models import Question, Answer
from ..forms import QuestionForm, AnswerForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def index(request):
    page = request.GET.get('page', '1')
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    return render(
        request=request,
        template_name='main/question_list.html',
        context={'question_list' : page_obj}
    )

@login_required(login_url='common:login')
def detail(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/question_detail.html', {'question':q})

pybo/main/views/model_views.py
import pickle
import re
import pandas as pd
import numpy as np
from keras.models import load_model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from konlpy.tag import Okt

print (">> MODEL LOAD")
model = load_model("./models/best_model.keras")

print (">> LABEL LOAD")
with open("./models/tokenizer.pickle", "rb") as f:
    tokenizer = pickle.load(f)

def predict_sentence_positivity(sentence:str)->dict:
    okt = Okt()
    stopwords = ['의','가','이','은','들','는','좀','잘','걍','과','도','를','으로','자','에','와','한','하다']
    max_len = 100
    new_sentence = re.sub(r'[^ㄱ-ㅎㅏ-ㅣ가-힣 ]','', sentence)
    new_sentence = okt.morphs(new_sentence, stem=True) # 토큰화
    new_sentence = [word for word in new_sentence if not word in stopwords] # 불용어 제거
    encoded = tokenizer.texts_to_sequences([new_sentence]) # 정수 인코딩
    pad_new = pad_sequences(encoded, maxlen = max_len) # 패딩
    score = float(model.predict(pad_new)) # 예측
    result = (score > 0.5)
    prob = "{:.2f}".format(score * 100) if result else "{:.2f}".format((1 - score) * 100)
    is_positive = (1 if result else 0)
    return {"is_positive" : is_positive, "prob" : prob}

pybo/main/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from ..models import Question, Answer
from ..forms import QuestionForm, AnswerForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='common:login')
def question_create(request):
    if request.method=='POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('main:index')
    else:
        form = QuestionForm()
    return render(request, 'main/question_form.html', {'form':form})


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "NOT AUTHORIZED TO EDIT")
        return redirect("main:detail", question_id = question.id)
    else:
        if request.method == "POST":
            form = QuestionForm(request.POST, instance=question)
            if form.is_valid():
                question = form.save(commit=False)
                question.author = request.user
                question.modify_date = timezone.now()
                question.save()
                return redirect("main:detail", question_id=question.id)
        else:
            form = QuestionForm(instance=question)
   
    context = {'form' : form}
    return render(request, 'main/question_form.html',context )

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "NoAuthDeletion")
        return redirect("main:detail", question_id=question.id)
    else:
        question.delete()
        return redirect('main:index')

pybo/templates/main/answer_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_error.html" %}
        <div class="form-group">
            <label for="content">Answer Contents</label>
            <textarea class="form-control" name="content" id="content" row="15">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

{% endblock %}

pybo/templates/main/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge badge-light p-2">
                    <div class="mb-2">{{ question.author.username }}</div>
                    {{ question.create_date }}
                </div>
                {% if request.user == question.author %}
                <div class="my-3">
                    <a href="{% url 'main:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">edit</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'main:question_delete' question.id %}">delete</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}} answers were given.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge badge-light p-2">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
                <div>
                    {% if answer.is_positive == 1 %}
                        <p style="display:inline">😄</p> 
                    {% else %}
                        <p style="display:inline">😡</p> 
                    {% endif %}
                        ({{answer.probability}}<p style="display:inline">&#x25</p>)
                </div>
                {% if request.user == answer.author %}
                     <div class="my-3">
                        <a href="{% url 'main:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">edit</a>
                     </div>
                     <div class="my-3">
                        <a href="#" class="btn btn-sm btn-outline-secondary" data-uri="{% url 'main:answer_delete' answer.id %}">delete</a>
                     </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'main:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="Submit Answer" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function(){
            if(confirm("Delete this question?")){
                location.href = $(this).data('uri');
            }
        });
    })
</script>
{% endblock %}

pybo/templates/main/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Ask Question</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">Title</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">Contents</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

pybo/templates/main/question_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>Number</th>
            <th>Title</th>
            <th>Author</th>
            <th>Created Date</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <!-- num = whole_len - start_index - cur_index + 1-->
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <a href="{% url 'main:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">({{ question.answer_set.count }})</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">No Data.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- paginator start -->
    <ul class="pagination justify-content-center">
        <!-- previous page -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">prev</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">prev</a>
        </li>
        {% endif %}
        <!-- page list -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- next page -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">next</a>
        </li>
        {% endif %}
    </ul>
    <!-- paginator finished -->
    <a href="{% url 'main:question_create' %}" class="btn btn-primary">Ask Question</a>
</div>
{% endblock %}